- name: Set PPDM ASSET Assignment
  uri:
    method: POST
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/agents-update-sessions"
    body_format: json 
    body: 
      hosts: "{{ update_hosts }}"
      precheckOnly: "{{ precheckOnly }}"
#      scheduledAt: "{{ scheduledAt }}"
      name: "{{ name }}"
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"    
    status_code: 200,201,202,204,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    agent_update: "{{ result }}"